import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Icon } from '../brand/Icon';
export function StopRow({ stop, order, isConfirmed, onPress }) {
    return (_jsxs("button", { onClick: () => !isConfirmed && onPress(stop), disabled: isConfirmed, style: {
            display: 'flex',
            alignItems: 'center',
            gap: 10,
            padding: '12px 16px',
            minHeight: 44,
            width: '100%',
            border: 'none',
            background: 'transparent',
            cursor: isConfirmed ? 'default' : 'pointer',
            textAlign: 'left',
        }, children: [_jsx("div", { style: {
                    width: 22,
                    height: 22,
                    borderRadius: 99,
                    background: 'var(--color-surface-2)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                }, children: _jsx("span", { style: {
                        fontFamily: 'var(--font-display)',
                        fontSize: 12,
                        fontWeight: 800,
                        color: 'var(--color-text-sec)',
                        lineHeight: 1,
                    }, children: order }) }), _jsx("div", { style: {
                    width: 28,
                    height: 28,
                    borderRadius: 9,
                    border: `2px solid ${isConfirmed ? 'var(--color-good)' : 'var(--color-border)'}`,
                    background: isConfirmed ? 'var(--color-good)' : 'transparent',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                    transition: 'all 0.15s',
                }, children: isConfirmed && _jsx(Icon, { name: "check", size: 16, color: "#fff" }) }), _jsxs("div", { style: { flex: 1, minWidth: 0 }, children: [_jsx("p", { style: {
                            fontFamily: 'var(--font-body)',
                            fontSize: 15,
                            fontWeight: 700,
                            color: 'var(--color-text)',
                            margin: 0,
                            textDecoration: isConfirmed ? 'line-through' : 'none',
                            opacity: isConfirmed ? 0.5 : 1,
                            transition: 'opacity 0.15s',
                            whiteSpace: 'nowrap',
                            overflow: 'hidden',
                            textOverflow: 'ellipsis',
                        }, children: stop.block ? `${stop.block} — Apto ${stop.apartment}` : `Apto ${stop.apartment}` }), _jsx("p", { style: {
                            fontFamily: 'var(--font-body)',
                            fontSize: 12,
                            fontWeight: 700,
                            color: 'var(--color-text-ter)',
                            margin: 0,
                            whiteSpace: 'nowrap',
                            overflow: 'hidden',
                            textOverflow: 'ellipsis',
                        }, children: stop.clientName })] }), _jsxs("span", { style: {
                    fontFamily: 'var(--font-display)',
                    fontSize: 15,
                    fontWeight: 800,
                    color: 'var(--color-accent)',
                    marginLeft: 'auto',
                    flexShrink: 0,
                }, children: [stop.quantity, "x"] })] }));
}
