name: Run Cheirin de Pao FRONTEND

on:
  push:
    branches:
      - '**'

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      pull-requests: write # to be able to comment on released pull requests
    outputs:
      created_pre_release_tag: ${{ steps.get_tag.outputs.created_pre_release_tag }}
      before_release_tag: ${{ steps.before_release_tag.outputs.before_release_tag }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configurando Node 22
        uses: actions/setup-node@v6
        with:
          node-version: 22.20.x

      - name: Instalar dependencia da release semantica https://www.npmjs.com/package/semantic-release
        run: npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      
      - name: Obter o nome da versão anterior
        id: before_release_tag
        run: |
          BEFORE_RELEASE_TAG=$(git describe --tags --abbrev=0 --match 'frontend-v*' 2>/dev/null || echo "")
          echo "before_release_tag=$BEFORE_RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "Tag anterior $BEFORE_RELEASE_TAG"

      - name: Criar Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --tag-format 'frontend-v${version}'

      - name: Baixar tags mais recentes
        run: git fetch --tags --force

      - name: Obtem o nome da versão criada
        id: get_tag
        run: |
          CREATED_PRE_RELEASE_TAG=$(git describe --tags --abbrev=0 --match 'frontend-v*' 2>/dev/null || echo "")
          echo "created_pre_release_tag=$CREATED_PRE_RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "Tag criada $CREATED_PRE_RELEASE_TAG"

  buildar_imagem_docker:
    needs: release
    if: needs.release.outputs.before_release_tag != needs.release.outputs.created_pre_release_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: criando arquivo .env de teste
        if: github.ref == 'refs/heads/development'
        run: |
          touch ./apps/web/.env.production
          echo VITE_API_URL=${{ secrets.API_URL_DEV }} >> ./apps/web/.env.production
          echo VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY_DEV }} >> ./apps/web/.env.production
          echo VITE_ONESIGNAL_APP_ID=${{ secrets.ONESIGNAL_APP_ID_DEV }} >> ./apps/web/.env.production
          echo VITE_SUPPORT_WHATSAPP=${{ secrets.SUPPORT_WHATSAPP_DEV }} >> ./apps/web/.env.production


      - name: criando arquivo .env de producao
        if: github.ref == 'refs/heads/main'
        run: |
          touch ./apps/web/.env.production
          echo VITE_API_URL=${{ secrets.API_URL_PROD }} >> ./apps/web/.env.production
          echo VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY_PROD }} >> ./apps/web/.env.production
          echo VITE_ONESIGNAL_APP_ID=${{ secrets.ONESIGNAL_APP_ID_PROD }} >> ./apps/web/.env.production
          echo VITE_SUPPORT_WHATSAPP=${{ secrets.SUPPORT_WHATSAPP_PROD }} >> ./apps/web/.env.production

      - name: logando no Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx (DOCKER CLI plugin)
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sistema_rebaixa:app_cheirin_pao_frontend_${{ needs.release.outputs.created_pre_release_tag }}

  deploy:
    needs: [release, buildar_imagem_docker]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v6

      - name: Instalar Ansible
        run: sudo apt update && sudo apt install -y ansible

        
      - name: Configurando variaveis de ambiente da aplicação de desenvolvimento
        if: github.ref == 'refs/heads/development'
        run: |
          echo "APP_PORT=${{ secrets.APP_PORT_DEV }}" >> $GITHUB_ENV
          echo "SERVICE_TYPE=dev" >> $GITHUB_ENV
        
      - name: Configurando variaveis de ambiente da aplicação de produção
        if: github.ref == 'refs/heads/main'
        run: |
          echo "APP_PORT=${{ secrets.APP_PORT_PROD }}" >> $GITHUB_ENV
          echo "SERVICE_TYPE=prod" >> $GITHUB_ENV
        
      - name: Criar o .env
        env:
          IMAGE_VERSION: ${{ needs.release.outputs.created_pre_release_tag }}
        run: |
          echo "release tag: $IMAGE_VERSION"
          echo DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} > .env
          echo IMAGE_VERSION=$IMAGE_VERSION >> .env
          echo APP_PORT=$APP_PORT >> .env
          echo SERVICE_TYPE=$SERVICE_TYPE >> .env
          more .env
        
      - name: Adicionar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_DEV }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          ssh-keyscan -H ${{ secrets.SSH_HOST_DEV }} >> ~/.ssh/known_hosts

      - name: criar arquivo variables.yml diretorio de desenvolvimento
        if: github.ref == 'refs/heads/development'
        run: |
          echo "workdir: ${{ secrets.WORKDIR_FRONTEND_DEV }}" > ./ansible/variables.yml
          echo "localdir: ${{ secrets.LOCALDIR_FRONTEND_DEV }}" >> ./ansible/variables.yml
      
      - name: criar arquivo variables.yml diretorio de produção
        if: github.ref == 'refs/heads/main'
        run: |
          echo "workdir: ${{ secrets.WORKDIR_FRONTEND_PROD }}" > ./ansible/variables.yml
          echo "localdir: ${{ secrets.LOCALDIR_FRONTEND_PROD }}" >> ./ansible/variables.yml
        
          
      - name: Criar arquivo de inventário do Ansible
        run: |
          echo "[servidores]" > ./ansible/hosts.ini
          echo "meu-servidor ansible_host=${{ secrets.SSH_HOST_DEV }} ansible_user=${{ secrets.SSH_USER_DEV }} ansible_become_password=${{ secrets.SSH_PASSWORD_DEV }} ansible_ssh_private_key_file=~/.ssh/key.pem" >> ./ansible/hosts.ini

      - name: Executar playbook do Ansible
        run: ansible-playbook -i ./ansible/hosts.ini ./ansible/playbook.yml